# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 20

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 7

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - is:bug
  - is:enhancement
  - is:discussion

# Label to use when marking as stale
staleLabel: status:stale

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  activity in the last 20 days. It will be closed if no further activity
  occurs within the next seven days. Thank you for your contributions.

# Limit to only `issues` or `pulls`
only: issues
