language: android

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

sudo: false

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - doc-28

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true