language: android

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

sudo: false

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    # https://developer.android.com/studio/releases/build-tools
    - build-tools-29.0.0
    - android-29
    - doc-29

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true