# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# Renaming ? Change the README badge.
name: 'Build'
on:
  push:
    branches:
      - main
  pull_request:

jobs:

  ANDROID_BASE_CHECKS:
    name: 'Base Checks'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: 'Perform base checks'
        run: ./gradlew app:assembleDebug library:dokkaJavadoc

  ANDROID_UNIT_TESTS:
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
      - name: 'Execute unit tests'
        run: ./gradlew library:testDebugUnitTest